sudo: false
language: node_js
# before_install:
#   - openssl aes-256-cbc -K $encrypted_ebdff555cfdd_key -iv $encrypted_ebdff555cfdd_iv -in id_rsa.pub.enc -out ~\/.ssh/id_rsa.pub -d
install:
  - npm install
  - ./scripts/generate.sh 3.5
after_success:
  - ./scripts/deploy.sh
# branches:
#   only:
#     - gh-pages
env:
  global:
  - ENCRYPTION_LABEL: "ebdff555cfdd"
  - COMMIT_AUTHOR_EMAIL: "you@example.com"